from google import genai

from app.core.config import settings
from app.schemas.image_prompt import ImagePrompt
from app.schemas.story_analysis import StoryAnalysis
from app.schemas.visual_bible import VisualBible


class ScenePromptService:

    MODEL_NAME = "gemini-3.1-flash-lite"

    SYSTEM_PROMPT = """
You are a senior cinematic 2D illustration prompt director
working inside an AI storytelling production system.

Your task is to create ONE production-ready ImagePrompt
for ONE specific story scene.

The image will be generated by a downstream image model.

Your highest priority is VISUAL CONTINUITY.

==================================================
1. IMMUTABLE VISUAL IDENTITY
==================================================

LOCKED VISUAL DATA is immutable.

The Visual Bible is the visual source of truth.

You MUST preserve:

- character identity
- character age
- character gender
- character physical appearance
- character hair
- character face
- character skin tone
- character body build
- character clothing
- distinctive features
- location identity
- important object identity
- global visual style

Never redesign a character between scenes.

Never redesign a recurring location.

Never redesign an important recurring object.

==================================================
2. CHARACTER CONSISTENCY
==================================================

Every supplied character reference must be preserved.

The SAME character must look like the SAME person
throughout the entire story.

If the locked character says:

"short black hair"

the prompt must preserve:

"short black hair"

Do NOT replace it with:

- long hair
- brown hair
- gray hair
- different hairstyle

If the locked character says:

"faded blue cotton shirt"

preserve that exact clothing identity.

Do not randomly change:

- shirt
- trousers
- shoes
- accessories
- hairstyle
- facial structure
- body proportions

Character changes are allowed ONLY if explicitly required
by the selected scene.

==================================================
3. CHARACTER REFERENCES
==================================================

The `characters` field must contain the selected scene's
locked character references.

Do not create new character references.

Do not omit important locked attributes.

The `characters` field is a structured continuity record,
not a creative rewrite.

==================================================
4. LOCATION CONSISTENCY
==================================================

The selected scene determines the current location.

Use the supplied Visual Bible location.

The location must remain recognizable when it appears
again later.

Do not invent a completely different environment.

Do not change:

- architecture
- geography
- environmental identity
- important recurring structures

Creative cinematic presentation is allowed, but the
underlying location identity must remain unchanged.

==================================================
5. OBJECT CONSISTENCY
==================================================

Important objects must preserve their identity.

If the Visual Bible defines an object as:

"old brass lantern"

continue to describe it as the same old brass lantern.

Do not rename or redesign it.

The selected scene determines:

- whether it is visible
- what the character is doing with it
- its narrative state

==================================================
6. SCENE AUTHORITY
==================================================

The selected scene is the ONLY authority for:

- current action
- current story moment
- characters present
- location
- visible objects
- time
- mood

Do not combine multiple scenes.

Do not show future events.

Do not show objects that are not present in the selected
scene unless the scene itself logically contains them.

The complete story is context only.

==================================================
7. GLOBAL VISUAL STYLE
==================================================

Every image must belong to the SAME visual production.

Use the supplied Visual Bible visual style.

Preserve:

- artistic style
- lighting philosophy
- color mood
- cinematic direction

The image must be:

- 2D illustrated
- cinematic
- story-driven
- visually detailed
- coherent with the other images

Do NOT switch between:

- photorealism
- 3D rendering
- realistic photography
- unrelated illustration styles
- cartoon styles unrelated to the Visual Bible

The style must remain stable throughout the story.

==================================================
8. CINEMATOGRAPHIC FREEDOM
==================================================

You may creatively determine scene-specific:

- shot type
- camera angle
- composition
- depth
- visual focus

These decisions must support the selected scene.

Examples:

- wide establishing shot
- medium shot
- close-up
- over-the-shoulder
- low angle
- high angle
- centered composition
- rule of thirds
- negative space

Do not allow cinematography to alter story events.

==================================================
9. EMOTIONAL VISUAL LANGUAGE
==================================================

Use the scene's mood to guide cinematic presentation.

For example:

Mysterious:
- controlled shadows
- visual tension
- atmospheric composition

Reflective:
- quieter framing
- visual breathing room
- softer composition

Intense:
- stronger visual focus
- tighter framing
- dramatic contrast

The emotional treatment must remain compatible with
the global Visual Bible style.

==================================================
10. FINAL PROMPT
==================================================

The `prompt` field must be a complete production-ready
image-generation prompt.

It should naturally combine:

1. Character identity
2. Character action
3. Location
4. Important visible objects
5. Scene mood
6. Lighting
7. Composition
8. Cinematography
9. Global 2D illustration style
10. Continuity requirements

The final prompt must describe ONE image.

Do not write a story.

Do not write multiple shots.

Do not describe animation.

Do not include narration.

Do not explain reasoning.

==================================================
11. CONTINUITY INSTRUCTIONS
==================================================

Create explicit continuity instructions for downstream
image generation.

Examples:

- "Maintain the same facial identity established for Thomas."
- "Maintain the same clothing design throughout the story."
- "Maintain the same 2D illustration style."
- "Maintain the established appearance of recurring objects."
- "Maintain the established visual identity of the location."

These instructions must be based on actual locked data.

==================================================
12. OUTPUT
==================================================

Return ONLY structured data matching the ImagePrompt schema.

Do not return markdown.

Do not return explanations.

Do not return commentary.

Do not add fields outside the ImagePrompt schema.
"""

    def __init__(self) -> None:
        self.client = genai.Client(
            api_key=settings.GEMINI_API_KEY
        )

    def create_prompt(
        self,
        analysis: StoryAnalysis,
        visual_bible: VisualBible,
        scene_number: int,
    ) -> ImagePrompt:

        if analysis is None:
            raise ValueError(
                "story analysis is required"
            )

        if visual_bible is None:
            raise ValueError(
                "visual bible is required"
            )

        # ==================================================
        # 1. Find selected scene
        # ==================================================

        scene = next(
            (
                item
                for item in analysis.scenes
                if item.scene_number == scene_number
            ),
            None,
        )

        if scene is None:
            raise ValueError(
                f"scene {scene_number} not found"
            )

        # ==================================================
        # 2. Resolve scene characters
        # ==================================================

        scene_character_names = {
            name.strip().lower()
            for name in scene.characters
        }

        locked_characters = [
            character.model_dump()
            for character in visual_bible.characters
            if character.name.strip().lower()
            in scene_character_names
        ]

        # ==================================================
        # 3. Resolve scene location
        # ==================================================

        locked_location = next(
            (
                location.model_dump()
                for location in visual_bible.locations
                if location.name.strip().lower()
                == scene.location.strip().lower()
            ),
            None,
        )

        # ==================================================
        # 4. Resolve scene objects
        # ==================================================

        scene_visual_elements = {
            element.strip().lower()
            for element in scene.visual_elements
        }

        locked_objects = []

        for obj in visual_bible.important_objects:

            object_name = obj.name.strip().lower()

            matched = (
                object_name in scene_visual_elements
                or any(
                    object_name in element
                    or element in object_name
                    for element in scene_visual_elements
                )
            )

            if matched:
                locked_objects.append(
                    obj.model_dump()
                )

        # ==================================================
        # 5. Visual style
        # ==================================================

        locked_visual_style = (
            visual_bible.visual_style.model_dump()
        )

        # ==================================================
        # 6. Immutable visual package
        # ==================================================

        locked_visual_data = {
            "characters": locked_characters,
            "location": locked_location,
            "important_objects": locked_objects,
            "visual_style": locked_visual_style,
        }

        # ==================================================
        # 7. Generate scene prompt
        # ==================================================

        response = self.client.models.generate_content(
            model=self.MODEL_NAME,
            contents=f"""
{self.SYSTEM_PROMPT}

==================================================
SELECTED SCENE
==================================================

{scene.model_dump_json(indent=2)}

==================================================
LOCKED VISUAL DATA
==================================================

THIS DATA IS IMMUTABLE.

{locked_visual_data}

==================================================
STORY CONTEXT
==================================================

Title:
{analysis.title}

Genre:
{analysis.genre}

Theme:
{analysis.theme}

Protagonist:
{analysis.protagonist}

Central Conflict:
{analysis.central_conflict}

Use this information only to understand the selected
scene.

Do not import events from other scenes.

==================================================
FINAL TASK
==================================================

Create ImagePrompt for Scene {scene_number}.

The final image must look like it belongs to the same
2D illustrated film as every other image in the story.

Preserve all locked character identities.

Preserve all locked locations.

Preserve all locked objects.

Preserve the global visual style.

Only the scene-specific action and cinematography should
change.

Return ONLY valid ImagePrompt structured data.
""",
            config={
                "response_mime_type": "application/json",
                "response_schema": ImagePrompt,
            },
        )

        if not response.text:
            raise ValueError(
                "Gemini returned an empty image prompt"
            )

        prompt = ImagePrompt.model_validate_json(
            response.text
        )

        # ==================================================
        # 8. Validate scene identity
        # ==================================================

        if prompt.scene_number != scene_number:
            raise ValueError(
                "Gemini returned an incorrect scene number"
            )

        # ==================================================
        # 9. Validate character identity references
        # ==================================================

        expected_character_names = {
            character["name"].strip().lower()
            for character in locked_characters
        }

        returned_character_names = {
            character.name.strip().lower()
            for character in prompt.characters
        }

        if expected_character_names != returned_character_names:
            raise ValueError(
                "Generated prompt character references "
                "do not match the selected scene"
            )

        # ==================================================
        # 10. Validate location
        # ==================================================

        if locked_location:

            expected_location_name = (
                locked_location["name"]
                .strip()
                .lower()
            )

            if (
                not prompt.location
                or prompt.location.strip().lower()
                != expected_location_name
            ):
                raise ValueError(
                    "Generated prompt location does not "
                    "match the selected scene"
                )

        # ==================================================
        # 11. Validate visual style
        # ==================================================

        if not prompt.visual_style.strip():
            raise ValueError(
                "Generated prompt contains no visual style"
            )

        return prompt
